In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('iaea-modaria-ii-tropical-dataset.csv', header=None)

# Preview the data
df.head()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,Record,Element,Radionuclide,Common name,Latin name,Compartment,CR,Uncert._CR,N_CR,Min_CR,...,OM,Exch. K,Exch. Ca,Exch. Mg,CEC,pH,QC meas.,QC sampl.,QC equip.,Reference
1,1,Cr,NaN,Potato,Solanum tuberosum,Tubers,3.60E-02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1
2,2,Co,NaN,Potato,Solanum tuberosum,Tubers,1.70E-02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1
3,3,Ni,NaN,Potato,Solanum tuberosum,Tubers,3.70E-02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1
4,4,Cu,NaN,Potato,Solanum tuberosum,Tubers,2.50E-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1

In [4]:
# List of all column names as per the dataset documentation
column_names = [
    'Record', 'Element', 'Radionuclide', 'Common name', 'Latin name', 'Compartment', 'CR', 'Uncert._CR', 'N_CR',
    'Min_CR', 'Max_CR', 'C_plant', 'Uncert._C_plant', 'N_plant', 'C_soil', 'Uncert._C_soil', 'N_soil',
    'Country', 'Site', 'K-G class', 'Contamination', 'Experiment', 'Year', 'Growth stage', 'Dry fraction',
    'Preparation', 'Soil depth', 'Texture', 'Sand', 'Silt', 'Clay', 'OM', 'Exch. K', 'Exch. Ca', 'Exch. Mg',
    'CEC', 'pH', 'QC meas.', 'QC sampl.', 'QC equip.', 'Reference'
]

In [8]:
# we need to do abit of cleaning by Keeping only rows with valid Element, Latin name, and CR
df_clean = df[['Element', 'Latin name', 'Common name', 'Compartment', 'CR']].copy()
df_clean = df_clean.dropna(subset=['Element', 'Latin name', 'CR'])

# Convert CR to numeric, coerce errors (e.g. empty or invalid) to NaN, then drop them
df_clean['CR'] = pd.to_numeric(df_clean['CR'], errors='coerce')
df_clean = df_clean.dropna(subset=['CR'])

# Optional: Remove zero or negative CRs (if scientifically justified)
df_clean = df_clean[df_clean['CR'] > 0]

df_clean.head()

KeyError: "None of [Index(['Element', 'Latin name', 'Common name', 'Compartment', 'CR'], dtype='object')] are in the [columns]"